### ISSUE TITLE
projectile-rails-on no longer hooking into projectile-mode

### ISSUE THREAD

**Issue by imtayadeway** [asok/projectile-rails#105]
I just upgraded emacs to version 26.0.50.1, projectile to version 20161008.47 and projectile-rails to 20160923.708. In my init.el:

```elisp
(projectile-global-mode)

;;;

(add-hook 'projectile-mode-hook 'projectile-rails-on)
```

This used to work great for me, but now projectile-rails fails to activate. Projectile seems to be working fine, however. I'm happy to help tackle this if it's an issue with projectile/projectile-rails, otherwise apologies :bowing_man:

**Comment by asok** [comment]
Thanks for reporting. But I cannot reproduce it. 
I've install 26.0.50.2 and run Emacs with `-Q` flag so my init file was not loaded. In the scratch buffer I've pasted:

```el
(require 'package)

;; Add MELPA before initialization
(add-to-list
 'package-archives
 '("melpa" . "http://melpa.org/packages/") t)

(package-initialize)

(package-refresh-contents)
(package-install 'projectile-rails)

(projectile-global-mode)

(add-hook 'projectile-mode-hook 'projectile-rails-on)
```
And then did `M-x eval-buffer RET`. So this bootstrapped melpa, installed projectile-rails and turned it on. I've browsed to the project but it was working alright.
Maybe you could try to do the same? Let me know what error do you get and maybe paste a stacktrace.

**Comment by markkocera** [comment]
I have the same problem, projectile-rails-mode is no longer activated automatically. When I manually run `M-x projectile-rails-mode` it activates for the current buffer, and everything works fine for that buffer. After opening a different file in the project it fails to activate.

I tried it with your minimal init file but no difference, projectile does work. There are no errors.
I'm using Emacs 25.1.1.

**Comment by asok** [comment]
@markkocera what value do you get if you open the rails file and do `M-x eval-expression RET (projectile-project-p) RET`? And also when you do `M-x eval-expression RET (projectile-rails-root) RET`?

**Comment by markkocera** [comment]
@asok They both report the correct project root dir. I tried it with several rails sites.

**Comment by asok** [comment]
@markkocera do you see any errors in the *Messages* buffer?

**Comment by markkocera** [comment]
No, nothing. I've been trying to debug this, but nothing yet. Any hints?

**Comment by markkocera** [comment]
@asok It seems `projectile-rails-on` is never called, nothing gets printed to Messages. I changed the function to be interactive:

```
(defun projectile-rails-on ()
  "Enable `projectile-rails-mode' minor mode if this is a rails project."
  (interactive)
  (print "debugging")
  (print (projectile-project-p))
  (print (not (projectile-rails--ignore-buffer-p)))
  (print (projectile-rails-root))
  (print "---------------------")
  (when (and
         (projectile-project-p)
         (not (projectile-rails--ignore-buffer-p))
         (projectile-rails-root))
    (projectile-rails-mode +1)))
```

When I then call it with `M-x projectile-rails-on` in a Rails project, this gets printed to the Messages buffer:

```
"debugging"

"/path/to/rails/project"

t

"/path/to/rails/project"

"---------------------"
```

Maybe the problem is higher up.

**Comment by asok** [comment]
@markkocera when you manually call `projectile-rails-on` does turn on the mode?
Are you sure you have `(add-hook 'projectile-mode-hook 'projectile-rails-on)` in your init? Mind that it's `projectile-rails-on` not `projectile-rails-mode`.

**Comment by markkocera** [comment]
@asok Yes it turns on the mode, but again only for the current buffer, same as when I manually call `projectile-rails-mode.`

I'm very sure, I have been using projectile-rails for at least a year. It only stopped working after I recently updated my packages.

I was trying some things, when I change `(add-hook 'projectile-mode-hook 'projectile-rails-on)` to `(add-hook 'projectile-find-file-hook 'projectile-rails-on)`, it starts working. But only when I find a file through projectile. When I use the keybindings from projectile-rails, the mode is nog activated.

**Comment by derikson** [comment]
I believe this is caused by the change introduced in Projectile in bbatsov/projectile@6986e435e64e2f4ee43bf8093c11e1da5fb266fa. It makes projectile-mode global, which means projectile-mode-hook is no longer triggered when a new buffer is opened.

I fixed this problem in my init.el by making projectile-rails-mode global as well:
```elisp
(define-globalized-minor-mode projectile-rails-global-mode
  projectile-rails-mode
  projectile-rails-on)
(projectile-rails-global-mode)
```

**Comment by asok** [comment]
Thanks @derikson for finding that out. I'm on holiday right now and kinda busy. I could produce a fix for that on Monday. For the time being @markkocera you would have to do what derikson had.

**Comment by imtayadeway** [comment]
Thanks all for responding when I could not. Many thanks to @derikson for the solution. @asok LMK if I can help, happy to make a PR but deferring first to @derikson, since the solution is his.

**Comment by derikson** [comment]
@imtayadeway please, go ahead. I'm not planning on adding a PR. My solution works for me, but I'm not experienced enough in emacs development to know if it's the right / best way to do it.
