### ISSUE TITLE
Access projecttile-rails commands from .html.erb and .html.haml

### ISSUE THREAD

**Issue by cmrichards** [asok/projectile-rails#109]
It would be good If it was possible to access the projectile-rails commands from rails view files with extensions .html.erb or .html.haml.    Is there an easy way for me to add this functionality?

**Comment by asok** [comment]
That should work out of the box.
What version of projectile-rails are you using? How do you set it up?

**Comment by asok** [comment]
If you are using spacemacs there's an opend issue here https://github.com/syl20bnr/spacemacs/issues/2448

Basically you need to call `(projectile-rails-global-mode)` in your init file. Let me know if it helps.

**Comment by cmrichards** [comment]
I'm using the latest version of spacemacs (installed a few days ago) which installed projectile-rails for me, so I'm not sure which version it is, but I presume It's a recent one.

Where exactly do I put  (projectile-rails-global-mode) ?

**Comment by cmrichards** [comment]
v 0.200.5

**Comment by asok** [comment]
@cmrichards if you do `M-x projectile-rails-global-mode RET` does it work for you?

**Comment by cmrichards** [comment]
I can select  projectile-rails-find-model by pressing SPC SPC and doing a search in spacemacs for the command, but none of the shortcuts to projectile-rails, such as  ", r f m" work when viewing .html.haml files

**Comment by asok** [comment]
@cmrichards put `(projectile-rails-global-mode)` inside `dotspacemacs/user-config` function in your init.el file.
