### ISSUE TITLE
syntax error near unexpected token `('

### ISSUE THREAD

**Issue by unixc3t** [asok/projectile-rails#110]
my env
linux mint 64bit 
emacs 24.5.1 

the system default bash

when i use C-c r ! r 

the error is  /bin/bash: -c: line 0: syntax error near unexpected token `('

**Comment by asok** [comment]
Are you sure this is not an error connected with your setup? Maybe something in your `.bashrc`?

Could you also enable debug on error with `M-x toggle-debug-on-error RET` and run again. You should get a backtrace. Please paste it here.

**Comment by unixc3t** [comment]
@asok 

-*- mode: projectile-rails-compilation; default-directory: "~/projects/blog/" -*-
Projectile Rails Compilation started at Mon Dec 19 20:43:30

bundle exec rake (12.0.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of rake (12.0.0) has removed it. You'll need to update your bundle to a different version of rake (12.0.0) that hasn't been removed in order to install. (Bundler::GemNotFound)
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `bundle exec rake (12.0.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of rake (12.0.0) has removed it. You'll need to update your bundle to a different version of rake (12.0.0) that hasn't been removed in order to install. (Bundler::GemNotFound)'

Projectile Rails Compilation exited abnormally with code 1 at Mon Dec 19 20:43:30

--------------------
this is my gemfile

source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'rake','12.0.0'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'awesome_rails_console'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end




---------------------------------------------------
 rudy@rudy ~/projects/blog $ gem list | grep rake
rake (12.0.0)
 
------
rudy@rudy ~/projects/blog $ whereis rake
rake: /usr/bin/rake /usr/local/bin/rake /home/rudy/.rbenv/shims/rake

----
rudy@rudy ~/projects/blog $ ls -al /usr/bin/rake
lrwxrwxrwx 1 root root 28 Dec 19 20:37 /usr/bin/rake -> /home/rudy/.rbenv/shims/rake
rudy@rudy ~/projects/blog $ ls -al /usr/local/bin/rake
lrwxrwxrwx 1 root root 28 Dec 18 17:08 /usr/local/bin/rake -> /home/rudy/.rbenv/shims/rake


this is my .bashrc

`# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm|xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    if [[ ${EUID} == 0 ]] ; then
        PS1='${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\h\[\033[01;34m\] \W \$\[\033[00m\] '
    else
        PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\w \$\[\033[00m\] '
    fi
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h \w \$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias hp="http_proxy=http://localhost:8123"

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

if [ -x /usr/bin/mint-fortune ]; then
     /usr/bin/mint-fortune
fi


export GRADLE_HOME=/home/rudy/pro/sdkman/gradle
export GRADLE_BIN=$GRADLE_HOME/bin

export MAVEN_HOME=/home/rudy/pro/sdkman/maven
export MAVEN_BIN=$MAVEN_HOME/bin

export ANT_HOME=/home/rudy/pro/sdkman/ant
export ANT_BIN=$ANT_HOME/bin

export JAVA_HOME=/home/rudy/pro/sdkman/jdk1.8.0_112
export JAVA_BIN=$JAVA_HOME/bin

export KOTLIN_HOME=/home/rudy/pro/sdkman/kotlinc
export KOTLIN_BIN=$KOTLIN_HOME/bin

export PATH="$JAVA_HOME:$JAVA_BIN:$KOTLIN_HOME:$KOTLIN_BIN:$GRADLE_BIN:$MAVEN_BIN:$ANT_BIN:$PATH"


export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

export NVM_DIR="/home/rudy/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/rudy/.sdkman"
[[ -s "/home/rudy/.sdkman/bin/sdkman-init.sh" ]] && source "/home/rudy/.sdkman/bin/sdkman-init.sh"
`

**Comment by asok** [comment]
If you run `rake` in this project do you got the error? Is it the only project you have this error? Can you publish this repo so I can re-create the error?

**Comment by unixc3t** [comment]
@asok 
If I run rake in this project  in terminal , rake is ok 
 if i use emacs and run  C-c r ! r , the Error appear 

this is the project repo   
https://github.com/unixc3t/TempBlog

**Comment by asok** [comment]
@unixc3t I've cloned your repo and it works without problem. I would suggests that you load something to your shell environment when you start Emacs.

Maybe you could run Emacs with `-Q` switch. And in the scratch buffer paste and evaluate this:

``` el
(require 'package)

;; Add MELPA before initialization
(add-to-list
 'package-archives
 '("melpa" . "http://melpa.org/packages/") t)

(package-initialize)

(package-refresh-contents)
(package-install 'projectile-rails)

(projectile-rails-global-mode)
```

Now you could try testing running the rake command via C-c r ! r.

**Comment by unixc3t** [comment]
@asok  thank you very much . I will try it.
