### ISSUE TITLE
Deleted tag master

### ISSUE THREAD

**Issue by Silex** [asok/projectile-rails#111]
Hello,

I took the liberty of deleting the tag "master". This was very likely a mistake.

![screenshot from 2017-03-14 09-56-12](https://cloud.githubusercontent.com/assets/16015/23892867/a990ac7c-089c-11e7-823b-fd4ee0d932e3.png)

**Comment by Silex** [comment]
Also, I wanted to fix the tests but I'm not sure what to do. Should the test be modified or the command be fixed?

```
  Scenario: Running rails console
    Given I open the app file "app/models/user.rb"
    And I turn on projectile-rails-mode
    When I run "projectile-rails-console"
    Then I should be in buffer "*ruby*"
    And projectile-rails should be turned on
    When I type "1 + 1"
    And I open the app file "app/models/user.rb"
    When I run "projectile-rails-console"
    Then I should be in buffer "*ruby*"
      Expected to be in buffer '*ruby*', but was in '*ruby*<2>'
    And I should see "1 + 1"
```

**Comment by asok** [comment]
Hi,
thanks for taking the action on the incorrect tag.
The error is due to the fact that inf-ruby now supports multiple irb buffers. Instead of looking for the precise buffer name `*ruby*` I would look for a regexp `*ruby*(<[0-9]+>)?` (actually it's not a valid elisp regexp, I just wrote it to let you know what I mean).

**Comment by Silex** [comment]
Alright, so I'd fix the test. I'll make a PR.

**Comment by Silex** [comment]
You pushed the tag master again. Please run this in your local repo:

`git tad -d master`

**Comment by asok** [comment]
Thanks for having an eye on me on that :)
I've deleted that on 1 machine. I'm out of home but once I'm back I'll delete it also on the machine I have in my home.

**Comment by Silex** [comment]
Can we close this?

**Comment by asok** [comment]
Most certainly yes.
