### ISSUE TITLE
Integration with Helm

### ISSUE THREAD

**Issue by bolivier** [asok/projectile-rails#115]
Is there a way to connect the completing prompts to helm? 

I looked through the source, and based on a cursory analysis it looks like it should use the projectile completing system, which I've set to helm, but it isn't.

**Comment by bolivier** [comment]
Turns out `projectile-completion-system` variable wasn't set correctly.  That does rectify the issue.

**Comment by m31271n** [comment]
More details: `(setq projectile-completion-system 'helm)` does rectify the issue.
