### ISSUE TITLE
Support database migrations

### ISSUE THREAD

**Issue by mvitz** [asok/projectile-rails#121]
It would be handy to execute db migrations from within emacs as well.

**Comment by Silex** [comment]
Hum, I think `projectile-rails-rake` allows that?

**Comment by mvitz** [comment]
... I'm just stupid. My last contact with rails was with 2.3.7 and some early 3.x and I just learned that `db:migrate` should be executed via `bin/rails`. I knew it's just an alias for `rake db:migrate` but couldn't make the connection here.
