### ISSUE TITLE
Need to load this package after projectile?

### ISSUE THREAD

**Issue by re-mx** [asok/projectile-rails#127]
Hello:

If my `projectile` is placed in `after-init-hook`, do I need to put `projectile-rails` in `projectile-mode-hook`?

like this:
```
(add-hook 'projectile-mode-hook
            (lambda () (projectile-rails-global-mode projectilexf-mode)))
```

The above code is copied from purcell/emacs.d.

Thank you

**Comment by asok** [comment]
Hi. Since there is a global mode for `projectile-rails` you should be fine calling `projectile-rails-global-mode` outside of the `projectile-rails-mode-hook`.
Let me know otherwise.
