### ISSUE TITLE
Remove the default keymap prefix "C-c r"

### ISSUE THREAD

**Issue by hjpotter92** [asok/projectile-rails#138]
Taking cue from projectile mode, the default keymap binding to `C-c r` should be removed.

> Don't define `C-c` _letter_ as a key in Lisp programs. Sequences consisting of `C-c` and a letter (either upper or lower case) are reserved for users; they are the **only** sequences reserved for users, so do not block them.

https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html

**Comment by asok** [comment]
What do you suggest instead? `C-c C-r`? Also any idea how to communicate such change to the users?

**Comment by Silex** [comment]
I think he means to not bind it to anything and force the users to bind it themselves, like in projectile.

**Comment by hjpotter92** [comment]
What @Silex said. The mode map need not be bound.

**Comment by asok** [comment]
I just merged the PR that unbinds the keymap.
