### ISSUE TITLE
Symbol’s value as variable is void: auto-insert-alist

### ISSUE THREAD

**Issue by jmromer** [asok/projectile-rails#144]
I'm seeing the following error on startup:

```
projectile-rails--setup-auto-insert: Symbol’s value as variable is void: auto-insert-alist
```

```el
;; elpa/26.3/develop/projectile-rails-20200406.830/projectile-rails.el L934-948 

(defun projectile-rails--setup-auto-insert ()
  "Call `define-auto-insert' with condition for ruby files under the current project.

If `auto-insert-alist' holds already the condition for the current project it does nothing.
So it safe to call it many times like in a minor mode hook."
  (let* ((file-re (format "^%s.*\\.rb$" (projectile-rails-root)))
         (current-project-cond `(,file-re . "projectile-rails")))
    (unless (projectile-rails--auto-insert-setup-p current-project-cond)
      (define-auto-insert
        current-project-cond
        [
         (lambda () (insert (projectile-rails-corresponding-snippet)))
         projectile-rails-expand-yas-buffer
         ]
        ))))
```

For some reason no backtrace is produced with `debug-on-error` is enabled.

**Comment by jmromer** [comment]
Possibly related to #143? 
Temporarily worked around the issue by adding a check for `'auto-insert-alist`
    
```el
;; elpa/26.3/develop/projectile-rails-20200406.830/projectile-rails.el L941-942 

(unless (and (boundp 'auto-insert-alist)
             (projectile-rails--auto-insert-setup-p current-project-cond))
```

**Comment by dabrady** [comment]
I see this error only when attempting to open a file in a Rails project. Once I've tried to do that, I see it when trying to execute any command afterwards, such that my Emacs is essentially useless: a restart has been the only way I've found to get out of this state.

I have found that **manually loading the `autoinsert` library** before trying to open a Rails project resolves this dependency issue.

```lisp
M-x load-library RET autoinsert RET
```

Seems like a recent change (perhaps #143 as suggested by @jmromer) may have introduced a new dependency, or changed the order in which things are initialized such that this dependency is no longer met.

**Comment by polypressure** [comment]
Unfortunately, the [workaround](https://github.com/asok/projectile-rails/issues/144#issuecomment-609862686) suggested by @jmromer did not work for me, and I had to resort to the [manual workaround](https://github.com/asok/projectile-rails/issues/144#issuecomment-614110596) posted by @dabrady.

This might be a completely wrong thing to do, but to avoid having to manually load the autoload library on every restart, I added this to my `dotspacemacs/user-init`:

```elisp
  (load-library "autoinsert")
```

**Comment by seagle0128** [comment]
The simplest workaround is `(setq projectile-rails-expand-snippet nil)`.

**Comment by Silex** [comment]
Sorry guys! Pushed https://github.com/asok/projectile-rails/commit/11980b2bcb99208888856a9b8666ff329b6f0142 and hoping it fixes the problem, feel free to comment if you think the fix should be different.

**Comment by Silex** [comment]
@asok: just a notification FYI, took the liberty of fixing the problem directly instead of using a PR.

**Comment by asok** [comment]
I'm sorry guys for the inconvenience and a long reply. 

@Silex that was a good call. Thanks a lot!
