### ISSUE TITLE
Support irb >= v1.2

### ISSUE THREAD

**Issue by mkostick** [asok/projectile-rails#146]
When using irb v1.2.3, `projectile-rails-console` does not work.  The `inf-ruby` buffer shows what looks to be a control character, and I can't interact with it:

```
Loading development environment (Rails 6.0.3.2)
▽
```

When I invoke a rails console through the `inf-ruby-console-auto` function of `inf-ruby`, it works.  Looking at the code for that package, it passes the `--nomultiline` option to `irb` when the version is >= 1.2.0:

https://github.com/nonsequitur/inf-ruby/blob/9f0f79ff459c7c417e8931ca020db121e24b45b5/inf-ruby.el#L867
https://github.com/nonsequitur/inf-ruby/blob/9f0f79ff459c7c417e8931ca020db121e24b45b5/inf-ruby.el#L110

If I set `projectile-rails-custom-console-command` to `"bundle exec rails console -- --nomultiline"`, `projectile-rails-console` works as expected:

```
Loading development environment (Rails 6.0.3.2)
2.7.1 :001 > 
```

**Comment by asok** [comment]
Thanks for pointing this out.
