### ISSUE TITLE
Improve Projectile Rails Server buffer (to improve emacs performance)

### ISSUE THREAD

**Issue by otavioschwanck** [asok/projectile-rails#148]
After a while, the logs from projectile-rails-server buffer starts to make emacs slow.  A hack that i made on doom is:

https://github.com/hlissner/doom-emacs/pull/4261 but it doen't work on old versions of rails.

Is possible to improve a way of projectile-rails handles the logs by default ?  Or maybe some option ?

O think a good way is limit the buffer line limit, when line limit reaches, clear the buffer with (comint-clear-buffer) (easy way) or maybe the new lines clears the old lines.

**Comment by asok** [comment]
This seems like a promising solution https://stackoverflow.com/a/11255400/710003
