### ISSUE TITLE
void-function projectile-rails-on

### ISSUE THREAD

**Issue by antono** [asok/projectile-rails#15]
Followed the instruction and got following error when visiting file in rails project:

```
 Error in post-command-hook (projectile-global-mode-check-buffers): (void-function projectile-rails-on)
```

**Comment by michaeldickens** [comment]
I am having this error. How did you fix it?

**Comment by asok** [comment]
@michaeldickens are you sure you have the `projectile-rails` in your load path? How do you installed it?
