### ISSUE TITLE
Not able to install via use-package: Required package ‘inflections-1.1’ is unavailable

### ISSUE THREAD

**Issue by fapdash** [asok/projectile-rails#159]
Config:
```
(use-package projectile-rails
  :ensure t
  :config
  (add-hook 'projectile-mode-hook 'projectile-rails-on))
```

I'm installing from Melpa.

Error:
```
Unable to activate package ‘projectile-rails’.
Required package ‘inflections-1.1’ is unavailable
```

Manual installation worked though.

**Comment by purcell** [comment]
Weird, `inflections` is definitely there in MELPA: https://melpa.org/#/inflections

I don't think this issue is at all specific to `projectile-rails`.

**Comment by fapdash** [comment]
Weird, but I also don't have time to investigate further.
Sorry for the confusion, closing.
