### ISSUE TITLE
Rake/Rails Can't Find Spring

### ISSUE THREAD

**Issue by tricon** [asok/projectile-rails#48]
Whenever I run a Rake or Rails command, it always uses `bundle exec` instead of `spring`.

I see that rake.el and projectile-rails.el both MD5 the project dir and PID path to determine if Spring is running. However, they never seem to locate it.

1. What can I do to troubleshoot the lookup of the PID file?
2. Shouldn't there be an option to always use `spring`? Spring will spawn a server upon first launch. Or is this an avoided complexity due to processes vs shells and sub-shells?

**Comment by asok** [comment]
Thanks for reporting and digging it. The thing is I do not use spring so it's hard for me to spot such issues.

Right now user has to be explicit about using a pre-loader (either by manually starting zeus or spring). I think it's a good thing. At least with zeus, I've found myself in situations when ActiveRecord had some quirks in pre-loaded environment. I had to stop zeus and re-ran a rake task in order for my code to work.

We could add a boolean variable for user to set if he wants to use spring. But it would be cumbersome if someone is working on many projects simultaneously. Another option is to ask bundler if spring (or zeus) is present in the Gemfile. But as I've stated before I like the explicitness of the current solution.

For now I think I could patch the code to check for both checksums (for old and new versions of spring).
@tricon what do you think?

**Comment by tricon** [comment]
I do think the explicitness is wise, in retrospect. If we could add a checksum for the new version, that would be the simplest solution.
