### ISSUE TITLE
projectile-rails-find-current-spec dependency on `rspec-mode`

### ISSUE THREAD

**Issue by a3ammar** [asok/projectile-rails#58]
The problem with it is that when I'm in a fixture file and execute `projectile-rails-find-current-spec`, `rspec-toggle-spec-and-target` creates a new spec file for the fixture. Would you be interested in a pull request that implements it in projectile?

Ideally it should handle it like `projectile-rails-find-current-view` where if it find multiple matching specs it asks which one the users wants. 

And it should also use `projectile-rails-fixture-dirs` to decide which `test/` or `spec/` to use, making `projectile-rails-find-current-test` obsolete.

**Comment by asok** [comment]
Yes it sounds interesting. I would happely accept such PR.
