### ISSUE TITLE
Version for melpa-stable?

### ISSUE THREAD

**Issue by shosti** [asok/projectile-rails#62]
It would be nice if there were a version of projectile-rails for melpa-stable (it definitely seems stable enough based on my usage). All that would be needed would be to make a version tag. In addition, projectile-rails currently requires projectile "1.0.0-alpha", which doesn't yet exist (so it's only compatible with the melpa version); it would be nice if it would be usable with the melpa-stable version of projectile (currently 0.12.0).

**Comment by asok** [comment]
I've tagged the project. Currently the latest version is v0.6.0. I myself am using  the unstable melpa.
So I would need someone who is using the stable melpa to confirm that the version v0.6.0 is compatible with the stable projectile.
