### ISSUE TITLE
How can I bind keys for running the default rake command?

### ISSUE THREAD

**Issue by semanticart** [asok/projectile-rails#63]
I'm a newcomer to emacs, so sorry for the probably obvious question:  I want to run the default task (my tests) via a key for projectile-rails-rake, but whenever I try to invoke it, I'm getting either a wrong-number-of-arguments or wrong types of arguments.

Can you point me in the right direction?

Thanks, I'm really enjoying the mode.

**Comment by asok** [comment]
Hmm can you be more specific? You are running `projectile-rails-rake` and you are getting the error?

**Comment by semanticart** [comment]
@asok sorry I wasn't more clear.

Everything works as expected out of the box. No bugs. :heavy_check_mark: 

`C-c r ! r RET` will run the default rake task. I'd like to bind that to something a little shorter that doesn't require a RET at the end (e.g. just `s-r`). 

( I know how to do keybindings but the ARG part of the `(projectile-rails-rake ARG)` is tripping me up. )

**Comment by semanticart** [comment]
A little more info:

I guess the ARG part is probably just the universal arguments and not my actual problem.

`(global-set-key (kbd "s-t") 'projectile-rails-rake)`

Launches the projectile-rails-rake interactive task picker but I still have to manually hit RET to run the default task

the macro `(global-set-key (kbd "s-t") (kbd "C-c r ! r"))` tries to run the task "[No match]"

**Comment by asok** [comment]
@semanticart I'm not sure that `(global-set-key (kbd "s-t") (kbd "C-c r ! r"))` can work as you expect. 
`kbd` returns a string, and `global-set-key` expects a symbol naming a command as the second argument.
But the main issue here is that I've implemented the code in the way that it is not possible to pass a name of a task to run.

Do you need to run the tests via rake? Or maybe you could use [rspec-mode](pezra/rspec-mode) or [ruby-test-mode](r0man/ruby-test-mode)?
Also you could try to do something like this:
```elisp
(defun run-default-rake-task ()
  (interactive)
  (compile "rake" 'projectile-rails-compilation-mode))

(define-key projectile-rails-mode-map (kbd "s-t") 'run-default-rake-task)
```

**Comment by semanticart** [comment]
@asok thanks for the advice. The provided code works great.

I'll check out those other two modes as well. Cheers!

**Comment by asok** [comment]
@semanticart of course if you are using bundler or some pre-loader raplece "rake" with i.e. "bundle exec rake".
