### ISSUE TITLE
Get projectile-project-root: Invalid function: "app/assets/javascripts/" when enabling projectile-rails

### ISSUE THREAD

**Issue by mlhamel** [asok/projectile-rails#64]
which basically prevent projectile-rails from working...

**Comment by asok** [comment]
What version of rails are you using?

**Comment by mlhamel** [comment]
I'm using 4.2.1

**Comment by asok** [comment]
I cannot reproduce it. 
What version of the projectile package are you using? Can you try to downgrade it and check if that helps?

**Comment by mlhamel** [comment]
Something was probably wrong with my packages installation, i've wiped everything and reinstall and it work ! Thanks :)

**Comment by KurtRMueller** [comment]
This is happening to me right now. @asok, what information do you need / is helpful?

**Comment by KurtRMueller** [comment]
@mlhamel Do you know what was wrong with your packages installation?

**Comment by mlhamel** [comment]
@KurtRMueller Sadly not. I've fixed it by purging my packages and reinstalled everything. Have you tried that?

**Comment by asok** [comment]
@KurtRMueller it's hard for me to tell what might be wrong. Can you post a stacktrace of the error? You can obtain it via `M-x toggle-debug-on-error RET` and then trying to enable the package.
From the top of my head, maybe you need to have a newer version of `projectile`?
