### ISSUE TITLE
Can't create a new file

### ISSUE THREAD

**Issue by stardiviner** [asok/projectile-rails#66]
My steps:
1. in controller file `articles.rb`
2. press `[C-c C-r V]` to find corresponding views file. (I set prefix to `[C-c C-r]`)
3. helm raise candidates `new.html.erb`, `edit.html.erb`.
4. I want to create a new views file: `create.html.erb`.
5. Input the filename, then I got this error by toggling option `debug-on-error`.

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil "/home/stardiviner/Code/learning/Ruby/Ruby on Rails/Tutorial/blog/")
  projectile-expand-root(nil)
  projectile-rails-goto-file(nil)
  projectile-rails-find-current-view()
  funcall-interactively(projectile-rails-find-current-view)
  call-interactively(projectile-rails-find-current-view nil nil)
  command-execute(projectile-rails-find-current-view)
```

I also tested in other cases:
  - [X] find-current
    - [X] view
  - [X] stylesheet
  - [X] find (not current)
All of them does not work.

**Comment by Silex** [comment]
As far as I know `C-c C-r V` is not meant to create views but to find existing ones. You are supposed to use the classic `C-x C-f` to create new files.

**Comment by stardiviner** [comment]
@Silex Yes, actually, I checked the source code and tried to improve it before I asked this issue.
It seems have the code to use `find-file`. but the condition is a littlle kind of weird. I can't understand what it does. So I hope someone can improve the code.

**Comment by asok** [comment]
> As far as I know C-c C-r V is not meant to create views but to find existing ones. You are supposed to use > the classic C-x C-f to create new files.

`C-c C-r V` tries to be smart - if no corresponding files exists it will present the user the list of files in the corredponding dir to choose from. So if you're completion system allows to input a non-existant file and create a new buffer for it it means that `C-c C-r V` can create new files.
 
I see the bug I'll try to reproduce it.

**Comment by stardiviner** [comment]
@asok Seems the fix still does not work.
I tested on my Emacs, it will open dired, instead of create a new file. (Maybe I mis-understand? this is the normal behavior?)
I tried to use edebug to debug,
but have not found wrong. And I don't know how to dig deeper.

![projectile-rails-find-view-create-new](https://cloud.githubusercontent.com/assets/378699/9839977/df35f49e-5abb-11e5-8c6a-281f6e18f748.png)

**Comment by asok** [comment]
@stardiviner it will open the dired buffer because your completion system does not allow inputting arbitrary value. Try using `ido` `(setq projectile-completion-system 'ido)`.
This is far from perfect but I don't know how to solve it. Maybe some message in mini-buffer would be explanatory.

**Comment by stardiviner** [comment]
@asok I see, I will open an issue on helm to see whether helm can support inputting arbitrary value feature. Thanks for your improvement.

**Comment by stardiviner** [comment]
@asok I found Helm has a source called `helm-source-buffer-not-found`, I will check it out to see whether can use that.

**Comment by asok** [comment]
@stardiviner there is an option to helm `:must-match 'confirm` option, and projectile is using it. And even if I eval `(helm-comp-read "Choose: " '("a" "b") :must-match 'confirm)` and then I input "c" and confirm the "c" is returned.
But when I eval `(helm-comp-read "Choose: " '("a" "b") :must-match 'confirm :candidates-in-buffer t)` an empty string is returned.
This way `helm-comp-read` is run in projectile. Look [here](https://github.com/bbatsov/projectile/blob/479c03642ffe50dfd88770ac55587f44c6c3c500/projectile.el#L1107).

**Comment by stardiviner** [comment]
So this means helm support for inputting arbitrary value, but need to modify projectile completing, will that affect other things?
