### ISSUE TITLE
Doesn't work when rails dir != git dir

### ISSUE THREAD

**Issue by Silex** [asok/projectile-rails#68]
Hello,

I have a project that is structured differently than the classic rails app:

``` shell
philippe@pv-desktop:~/work/project$ tree -d -L 2
.
├── apps
│   ├── nginx
│   └── rails
├── data
├── env
└── utils
```

Thus, `projectile-rails-root` is not the same as `projectile-project-root` and it fails... what do you reckon would be the easiest workaround/fix?

**Comment by Silex** [comment]
@asok: ping?

**Comment by asok** [comment]
@Silex sorry for not responding it seems that I've overlooked the notification for this issue.

So I guess under `apps/rails` you have your normal rails app, but you want `~/work/projects` to be treated as the root? Maybe the easiest would be to overwrite `projectile-rails-root` function after loading the package? Something like this:
```el
(eval-after-load 'projectile-rails
  (defun projectile-rails-root ()
    (projectile-project-root)))
```

**Comment by Silex** [comment]
@asok: hum, no that's already what it does...

The problem is that all the functions like `projectile-rails-find-controller` just assume everything is under `app/controllers` in the projectile-project-root no matter what projectile-rails-root says.

Here's my attempt:

``` elisp
(defun projectile-rails-root ()
  "Returns rails root directory if this file is a part of a Rails application else nil"
  (ignore-errors
    (let ((root (projectile-project-root)))
      (concat root "app/rails"))))
```

``` backtrace
Debugger entered--Lisp error: (file-error "Setting current directory" "No such file or directory" "/home/philippe/work/stvs/arqivis/app/controllers/")
  call-process("/bin/bash" nil t nil "-c" "git ls-files -zco --exclude-standard")
  apply(call-process "/bin/bash" nil t nil ("-c" "git ls-files -zco --exclude-standard"))
  process-file("/bin/bash" nil t nil "-c" "git ls-files -zco --exclude-standard")
  shell-command-to-string("git ls-files -zco --exclude-standard")
  projectile-files-via-ext-command("git ls-files -zco --exclude-standard")
  projectile-get-repo-files()
  projectile-dir-files-external("/home/philippe/work/stvs/arqivis/" "/home/philippe/work/stvs/arqivis/app/controllers/")
  projectile-dir-files("/home/philippe/work/stvs/arqivis/app/controllers/")
  projectile-rails-choices((("app/controllers/" "/controllers/\\(.+\\)_controller\\.rb$")))
  projectile-rails-find-controller()
  funcall-interactively(projectile-rails-find-controller)
  #<subr call-interactively>(projectile-rails-find-controller nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> projectile-rails-find-controller nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (projectile-rails-find-controller nil nil))
  call-interactively(projectile-rails-find-controller nil nil)
  command-execute(projectile-rails-find-controller)
```

**Comment by asok** [comment]
Maybe something like this:
```el
modified   projectile-rails.el
@@ -326,6 +326,9 @@ Returns a hash table with keys being short names and values being relative paths
       (maphash (lambda (key value) (setq keys (cons key keys))) hash)
       keys)))
 
+(defun projectile-rails--append-root-suffix (dirs)
+  (--map (format "%s%s%s" (projectile-project-root) "apps/rails/" it) dirs))
+
 (defmacro projectile-rails-find-resource (prompt dirs &optional newfile-template)
   "Presents files from DIRS to the user using `projectile-completing-read'.
 
@@ -333,7 +336,7 @@ If users chooses a non existant file and NEWFILE-TEMPLATE is not nil
 it will use that variable to interpolate the name for the new file.
 NEWFILE-TEMPLATE will be the argument for `s-lex-format'.
 The bound variable is \"filename\"."
-  `(let* ((choices (projectile-rails-choices ,dirs))
+  `(let* ((choices (projectile-rails-choices (projectile-rails--append-root-suffix ,dirs)))
           (filename (or
                      (projectile-completing-read ,prompt (projectile-rails-hash-keys choices))
                      (user-error "The completion system you're using does not allow inputting arbitrary value.")))

```
Though I haven't tested it. Probably you would have to change it slightly because `dirs` is a list of lists. So you would have to run `map` twice on it. (BTW I don't recall why I made it so :) )
Let me know how it worked out.

**Comment by Silex** [comment]
Hum, yeah I guess that would work... it's pretty hacky tho.

I can't help but feel that there is an unsolved problem reguarding `projectile-rails-root` because it's basically pretty useless at the moment.

IMHO there needs to be some refactoring so the detection of "rails project" is done in a better way. 

Right now it works like this:

- projectile-rails-root: checks if `projectile-project-root` contains `config/environment.rb`.
- All the finders ignore `projectile-rails-root` and use `projectile-dir-files` which uses on `projectile-project-root`.

I think it'd be better if it behaved like this:

- `projectile-rails-root`: use `projectile-locate-dominating-file` to find which parent directory contains `config/environment.rb`
- Refactor everything so it uses `projectile-rails-root` (probably as simple as writing a `projectile-rails-dir-files` function which does the right thing)

I'll see if I can hack something.

**Comment by asok** [comment]
@Silex I've added you as a collaborator to the project

**Comment by Silex** [comment]
:+1: :smile:

**Comment by Silex** [comment]
Ok, I started the work in another branch, you can look at the diff with https://github.com/asok/projectile-rails/compare/rails-root-improvements?expand=1

**Comment by asok** [comment]
Ok cool. Please make a PR. Travis should run it and we should see the result the tests. Unfortunately recently some of them fail, I was too lazy fix them. But if the same will fail as for the master branch we can merge it.

**Comment by Silex** [comment]
Alright, it's not done tho. It more or less works except I couldn't do the final steps (still have to fix `projectile-rails-goto-file` and friends)
