### ISSUE TITLE
Override ctags just for rails projects

### ISSUE THREAD

**Issue by lethjakman** [asok/projectile-rails#70]
So it's just an idea, but maybe it'd be a good idea to override the ctags generater with ripper-tags if it's available. It offers much better ruby support and I would love to have this happen in my rails projects.

**Comment by asok** [comment]
Hmm ctags are really more a feature of `projectile` the package that `projectile-rails` depends on. So this issue belongs more there than here, I guess.

**Comment by lethjakman** [comment]
I figured it was more of a projectile-rails thing since this would be a rails specific feature. I'm not sure they'd want to implement something that's ruby/rails specific unless you had per project ctag generation or something.

**Comment by asok** [comment]
Hmm sounds interesting. I don't use ctags, and I don't really have time for new features for the project.
Once I'll get some free time I'll try to look at it. In the meantime maybe someone will make a PR?

**Comment by asok** [comment]
I would envision this feature to be a part of a seperate package, that could also hook into projectile. That package would be specific to a ruby projects, not only rails. Thus closing this.
