### ISSUE TITLE
Yasnippet error for non-ruby files in project

### ISSUE THREAD

**Issue by Pitometsu** [asok/projectile-rails#71]
See: https://github.com/capitaomorte/yasnippet/issues/605

**Comment by stardiviner** [comment]
+1

**Comment by asok** [comment]
I think this https://github.com/asok/projectile-rails/commit/dd17165552381c6f2f41ab5b3a5bb5dc0d120753 should take care of it.

**Comment by Pitometsu** [comment]
Confirm: it's fixed. @stardiviner could you check it as well, please?

**Comment by stardiviner** [comment]
confirm fixed.
