### ISSUE TITLE
Scroll buffer

### ISSUE THREAD

**Issue by Pitometsu** [asok/projectile-rails#73]
On page refresh `projectile-rails` move point in current buffer, not in `*projectile-rails-server*`
And I got error:
```
error in process filter: smooth-scroll-up: End of buffer
error in process filter: End of buffer
```

**Comment by asok** [comment]
I cannot re-produce it. Maybe it's your setup? Do you have the same issue if you run via `emacs -Q`?

**Comment by Pitometsu** [comment]
@asok you right, without [smooth-scrolling](https://github.com/aspiers/smooth-scrolling#readme) it works well.

**Comment by Pitometsu** [comment]
Seems like it's *smooth-scrolling* [issue](https://github.com/aspiers/smooth-scrolling/issues/12).

**Comment by asok** [comment]
OK closing.

**Comment by Pitometsu** [comment]
@asok I investigated issue deeper. Sadly, seems like it's your bug. Could you replace `next-line` by `forward-line`, please?

**Comment by asok** [comment]
Done. Did it help?

**Comment by Pitometsu** [comment]
Yes, thanks a lot!

**Comment by asok** [comment]
OK thanks for your feedback.
