### ISSUE TITLE
Font lock do not play nice with enh-ruby-mode

### ISSUE THREAD

**Issue by Pitometsu** [asok/projectile-rails#76]
For example `render 'edit'` will be highlighted as
`  `**render** `'edit'`
It's ok. But if I'll comment it, highlighting do not dissapear:
`  `*#* **render** *'edit'*
It dissapear only after `M-x enh-ruby-mode`:
`  `*#* *render* *'edit'*

**Comment by asok** [comment]
Not sure if I can do something about it. This might be the limitations of enh-ruby-mode/font locking in Emacs.
