### ISSUE TITLE
Debugging with pry

### ISSUE THREAD

**Issue by Pitometsu** [asok/projectile-rails#77]
Can I switch `*projectile-rails-server*` on breakpoin such as  `binding.pry` or `byebug` into [inf-ruby](https://github.com/nonsequitur/inf-ruby/issues/79) mode like it [rspec-mode](https://github.com/pezra/rspec-mode/#debugging) does?

It work on `inf-ruby-switch-from-compilation`. Perhaps it will be better add tip in README?

**Comment by asok** [comment]
Hmm not sure. Once I have time I'll look into it.

**Comment by Pitometsu** [comment]
@asok now it just work, from **inf-ruby** side. Can you just add tip to README, please?

**Comment by asok** [comment]
@Pitometsu did you mean something like [this](https://github.com/asok/projectile-rails#debugging)?

**Comment by Pitometsu** [comment]
@asok cool, thank you!
