### ISSUE TITLE
Unable to interact with rails server

### ISSUE THREAD

**Issue by esjee** [asok/projectile-rails#85]
![2016-02-14-110709_621x249_scrot](https://cloud.githubusercontent.com/assets/2501554/13033132/89d562e6-d30b-11e5-9e2c-2ea5e624c0c5.png)

When using something like binding.pry to open a console, I'm unable to interact with the repl. Is this intentional?

(Note sure if it's noteworthy, but I'm using evil.)

**Comment by esjee** [comment]
Looking into it a bit more, it looks like the buffer is read-only. After changing that (C-x C-q (?)) it looks like everything works as expected.

Changing the buffer to not be read-only (much like rails-console) seems doable enough. Do you have any thoughts on this?

**Comment by stardiviner** [comment]
Are you using `pry-rails` in Rails as IRB replacement for rails console?

**Comment by esjee** [comment]
Yes, rails-console opens a pry shell, not IRB.

**Comment by stardiviner** [comment]
`inf-ruby` seems do not support `pry`.

**Comment by asok** [comment]
For me hitting C-x C-q didn't allow me to interact with pry.
I had to run `inf-ruby-switch-from-compilation` in order to do it.
![replace-dialog10](https://cloud.githubusercontent.com/assets/120457/13512347/57622310-e19a-11e5-889d-0c3f4bf829dd.png)
Although I had to manually delete the chars before the prompt.

**Comment by asok** [comment]
Oh the workaround for "�[0G[1] " is here #12

**Comment by asok** [comment]
@esjee are you calling `inf-ruby-auto-enter` somewhere in your setup? That would explain why you have compilation mode enabled right after hitting the breakpoint.

**Comment by esjee** [comment]
Sorry the for the late response!

I checked, and that was indeed the issue. Thanks for the help!
