### ISSUE TITLE
"You're not in a project" error inside symlinked app

### ISSUE THREAD

**Issue by asok** [asok/projectile-rails#88]
Reported in https://github.com/bbatsov/projectile/issues/376#issuecomment-191887987

@cybercode I tried recreating the bug on my machine but with no luck. What version of Emacs, projectile and projectile-rails are you using?

**Comment by cybercode** [comment]
GNU Emacs 25.1.50.5 (x86_64-apple-darwin15.3.0, NS appkit-1404.34 Version 10.11.3 (Build 15D21))
 of 2016-03-06

projectile*: melpa stable

BTW, in testing _sometimes_ i can exit emacs w/ `C-x C-c`, sometimes i have to force quit. The difference _may_ be related to whether or not a robe/rails subprocess is running.

**Comment by asok** [comment]
@cybercode sorry for the late response.
I've tried to reproduce the bug. For me it's working fine.

Maybe you could try to disable caching in projectile (setq projectile-enable-caching nil)? Or enable it if it's disabled.

Another thing, you could run emacs with -q flag, setup melpa, and install projectile-rails and see if the error persists in the bare Emacs.

**Comment by cybercode** [comment]
On Thu, Apr 07, 2016 at 01:02:46AM -0700, Adam Sokolnicki wrote:
>    @cybercode sorry for the late response.
>    I've tried to reproduce the bug. For me it's working fine.
> 
>    Maybe you could try to disable caching in projectile (setq
>    projectile-enable-caching nil)? Or enable it if it's disabled.
> 
>    Another thing, you could run emacs with -q flag, setup melpa, and install
>    projectile-rails and see if the error persists in the bare Emacs.

Tracked it down. If you have `projectile-global-mode` and
`(add-hook 'projectile-mode-hook 'projectile-rails-on))` the problem with
attempting to open a file in a soft-linked subdirectory. Without it, you don't
but then you need to attach projectile rails somewhere else to get it to work.

I'm not sure where to attach it to get projectile rails to work when you are
in an e.g., non-ruby file in a project.

rick

**Comment by asok** [comment]
@cybercode are you by any chance opening a file via tramp (that is on a remote server using Emacs)?

**Comment by cybercode** [comment]
No.

**Comment by asok** [comment]
@cybercode I think this https://github.com/asok/projectile-rails/commit/6d44cd771fc70adbf639f2f2a320fdcc88a5fb27 should do it. Please let me know if it helped.

**Comment by cybercode** [comment]
yes, thank you. Issue seems to be resolved.
