### ISSUE TITLE
Mercurial repos break projectile-rails-find-*

### ISSUE THREAD

**Issue by shreve** [asok/projectile-rails#89]
I've had mixed results with this issue. 

In an existing mercurial project, calling `projectile-rails-find-model` provides a list of all my models, but they include their relative path (`app/models/tag | app/models/ticket` , etc). When I select one, nothing happens. The file isn't opened.

When trying to reproduce this issue in a blank repo with a few example models, the correct behavior is observed until running `hg init`. Afterward, `projectile-rails-find-model` returns a blank list. I can type a model name and RET and the correct file opens.

These examples used model, but the issue is the same with all the find methods.

I'm using `emacs 24.51`, `projectile-20160321.2307`, and `projectile-rails-20160303.1450`.

**Comment by asok** [comment]
@shreve I'm afraid this is related to [projectile](https://github.com/bbatsov/projectile) which is what `projectile-rails` is based on .
From the top of my head - maybe you could try to disable/enable cache in projectile?

**Comment by shreve** [comment]
Thanks for pointing me in the right direction. I dug a little deeper and found where projectile-rails hooks into projectile for searching. I think the issue deals with [`projectile-get-repo-files`](https://github.com/bbatsov/projectile/blob/4eab3ef2e356756eb569261fb219d427772ef605/projectile.el#L981). I can't find the exact issue, but I found that switching the indexing mode to native foregoes the VCS, and fixes my issue! 

```lisp
;; ~/.emacs
(setq projectile-indexing-method 'native)
```

If I can figure out anything else, I'll open a ticket in their repo. Thanks for your service!
