### ISSUE TITLE
projectile-rails-server failed in zsh & chruby

### ISSUE THREAD

**Issue by gonglexin** [asok/projectile-rails#91]
I'm using chruby and zsh, but when I try to start rails server I got this error:

```
Projectile Rails Server started at Thu Mar 31 10:16:19

bundle exec rails server
Could not find rake-10.4.2 in any of the sources
Run `bundle install` to install missing gems.

Projectile Rails Server exited abnormally with code 7 at Thu Mar 31 10:16:20
```

it seems that `projectile-rails-server` is using my system ruby, not the ruby version set by chruby.

However, `projectile-rails-console` is ok to load by the correct ruby version.

**Comment by asok** [comment]
@gonglexin please install [chruby.el](https://github.com/plexus/chruby.el). Running console works fine probably because `inf-ruby` does some magic to run the correct ruby version.

**Comment by gonglexin** [comment]
@asok Actually, I do using chruby.el but no lucky:

<img width="830" alt="screen shot 2016-03-31 at 5 26 13 pm" src="https://cloud.githubusercontent.com/assets/48140/14171502/f08c2d02-f765-11e5-96f7-4857b4f8cbaf.png">

**Comment by asok** [comment]
If you do `M-x shell-command RET ruby -v RET` it gives you the correct ruby version?

**Comment by gonglexin** [comment]
Nope, it shows the system ruby version. I believe this is the root cause. however, I don't know how to fix it. Forgive me, I just try to use emacs recently as a 10 years vimer.

**Comment by gonglexin** [comment]
I believe this is a bug and it has nothing to do with `projectile-rails`. I just find that the $PATH is different between zsh and emacs. emacs add `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` at the beginning of the path. Do you have any idea about this?

$PATH in zsh shell:
```
/Users/gonglexin/.asdf/bin:/Users/gonglexin/.asdf/shims:/Users/gonglexin/.gem/ruby/2.2.3/bin:/Users/gonglexin/.rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/bin:/Users/gonglexin/.rubies/ruby-2.2.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin
```

$PATH in emacs (echo $PATH in `shell-command`)
```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/gonglexin/.asdf/bin:/Users/gonglexin/.asdf/shims:/Users/gonglexin/.gem/ruby/2.2.3/bin:/Users/gonglexin/.rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/bin:/Users/gonglexin/.rubies/ruby-2.2.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin
```

**Comment by gonglexin** [comment]
Meanwhile, I only got this error in emacs started in terminal. it runs ok in GUI version ([Emacs For Mac OS X](https://emacsformacosx.com/)).

**Comment by asok** [comment]
> Forgive me, I just try to use emacs recently as a 10 years vimer.

Welcome on board!
This doesn't have to be an Emacs bug. Please try starting Emacs with `-q` flag which will skip your config file. You could try installing chruby and projectile-rails from a scratch buffer and see if the bug is related to your setup.
In fact the shell variable in Emacs are a bit magic for me as well. I never had time to really dig into it.
When I was on Mac I used use https://github.com/purcell/exec-path-from-shell

If you are an ex-vimer I can recommend [spacemacs](http://spacemacs.org/) to you. The setup for ruby works quite well on the `develop` branch of the project.

**Comment by gonglexin** [comment]
Thanks @asok , I tried `prelude` and `spacemacs`, also tried starting Emacs with `-q` flag, no lucky again. It seems that `shell-command` will always add the paths in `/etc/paths` to the begin of the `$PATH` even I tried with `exec-path-from-shell`. So, I just add the ruby and gem bin paths at the very begining there. problem solved. however it's a tricky solution. Thanks for your help again :)

**Comment by WilsonChiang** [comment]
@gonglexin Could you detail how you manually added them? I'm having the same issue.

**Comment by gonglexin** [comment]
@WilsonChiang Add the ruby & gem paths in /etc/paths

```shell
$ cat /etc/paths
/Users/gonglexin/.rubies/ruby-2.2.3/bin
/Users/gonglexin/.gem/ruby/2.2.3/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```
