### ISSUE TITLE
Doesn't find stylesheets

### ISSUE THREAD

**Issue by cybercode** [asok/projectile-rails#92]
Recently, `projectile-rails-find-stylesheet` no longer finds any matches from `app/assets/stylesheets`. Verified in `emacs -q` and then explicitly loading libraries from a fresh melpa update.

**Comment by asok** [comment]
I cannot reproduce it.
What exactly is happening? Nothing happens when you run the command?

Maybe something wrong is happening because you are using a pre-loader? Please make sure that neither spring nor zeus are running. Do you have this issue on all rails projects?

**Comment by cybercode** [comment]
On Sat, May 07, 2016 at 02:36:53AM -0700, Adam Sokolnicki wrote:
>    I cannot reproduce it.
>    What exactly is happening? Nothing happens when you run the command?
> 
>    Maybe something wrong is happening because you are using a pre-loader?
>    Please make sure that neither spring nor zeus are running. Do you have
>    this issue on all rails projects?

No preloader, and it is only stylesheets; model, controllers, etc work
fine. Good call though, it is only on one project, but responds the same on
multiple computers.

I tried edebugging the call, but get lost in the macro... Any ideas where i
should look/set a breakpoint?

rick

**Comment by cybercode** [comment]
Followup--

It seems that in this project (only) `projectile-rails-stylesheet-dirs` is being set to `nil`.

**Comment by asok** [comment]
@cybercode [this](https://github.com/asok/projectile-rails/commit/f994baf135a7afd86f750c4467f4ed228b15c35d) should do it please let me know if not.
