### ISSUE TITLE
support navigate to config files

### ISSUE THREAD

**Issue by stardiviner** [asok/projectile-rails#93]
When adding I18n support, need to edit file `config/locales/en.yml`. And other files.
Hope projectile-rails can support this keybinding. Thanks in advance.

**Comment by asok** [comment]
@stardiviner hey there's already `projectile-rails-find-locale` command to find a locale file. Do you need something else? Like localizing a locale definition?
That would be totally awesome.

**Comment by stardiviner** [comment]
You're right, I found the command. Thanks.
