### ISSUE TITLE
Related files; S, V, and T variants

### ISSUE THREAD

**Issue by jkrmr** [asok/projectile-rails#95]
[vim-rails](https://github.com/tpope/vim-rails) can jump not only to alternate files (`:A`) but also related ones (`:R`). It also defines "S", "V", and "T" variants to open an alternate or related file in a split, vertical split, or new tab.

I'm curious if it would be feasible to implement comparable behavior in projectile-rails. I'm up for taking a stab at it if there's interest—this would be very useful to me, as `:AS` and `:RV` were go-tos for me in Vim.

**Comment by asok** [comment]
@jkrmr first of all [projectile](https://github.com/bbatsov/projectile) which this package depends on has `projectile-find-other-file`. There's also `projectile-find-other-file-other-window`.

Look at [evil-rails](https://github.com/antono/evil-rails). I think that if you would like to implement `:AS`, `:RV` you should do it for that package.

**Comment by jkrmr** [comment]
> first of all projectile which this package depends on has projectile-find-other-file. There's also projectile-find-other-file-other-window

Thanks, but I'm not able to get the desired behavior out of those -- I pretty much always just see `No other file found`.

> Look at evil-rails. I think that if you would like to implement :AS, :RV you should do it for that package

Oh that's right. That would be a more appropriate place for this, wouldn't it? Sorry about that. 🙇
