### ISSUE TITLE
Documentation on running tests

### ISSUE THREAD

**Issue by J3RN** [asok/projectile-rails#99]
In the README, it says
> ...greping (or acking) files, run tests, switch between projects, etc.

However, there is no further reference to running rails tests. Does this feature exist, and if it does, could we add some documentation to the README to show that?

**Comment by asok** [comment]
Hi,
actually in the README I'm mentioning [rspec-mode](pezra/rspec-mode). For test unit there's [ruby-test-mode](https://github.com/r0man/ruby-test-mode). I'll update the readme to inlude ruby-test-mode also.
